// <auto-generated />
using System;
using System.Collections.Generic;
using AquaPlan.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace AquaPlan.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AquaPlanDbContext))]
    [Migration("20260413081633_AddSectorEntity")]
    partial class AddSectorEntity
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("AquaPlan.Domain.Entities.AnalysisProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Category")
                        .HasColumnType("integer")
                        .HasColumnName("category");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_analysis_profiles");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_analysis_profiles_tenant_id_code");

                    b.ToTable("analysis_profiles", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.AnalysisProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_analysis_programs");

                    b.HasIndex("TenantId", "Code")
                        .IsUnique()
                        .HasDatabaseName("ix_analysis_programs_tenant_id_code");

                    b.ToTable("analysis_programs", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.AnalysisProgramProfile", b =>
                {
                    b.Property<Guid>("AnalysisProgramId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_program_id");

                    b.Property<Guid>("AnalysisProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_profile_id");

                    b.HasKey("AnalysisProgramId", "AnalysisProfileId")
                        .HasName("pk_analysis_program_profiles");

                    b.HasIndex("AnalysisProfileId")
                        .HasDatabaseName("ix_analysis_program_profiles_analysis_profile_id");

                    b.ToTable("analysis_program_profiles", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.AppUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer")
                        .HasColumnName("access_failed_count");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("text")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("email");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("email_confirmed");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("external_id");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("first_name");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("last_name");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("lockout_enabled");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("lockout_end");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_email");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_user_name");

                    b.Property<string>("Organization")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("organization");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text")
                        .HasColumnName("password_hash");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text")
                        .HasColumnName("phone_number");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean")
                        .HasColumnName("phone_number_confirmed");

                    b.Property<string>("RefreshToken")
                        .HasColumnType("text")
                        .HasColumnName("refresh_token");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("refresh_token_expiry_time");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text")
                        .HasColumnName("security_stamp");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean")
                        .HasColumnName("two_factor_enabled");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_users");

                    b.HasIndex("ExternalId")
                        .IsUnique()
                        .HasDatabaseName("ix_asp_net_users_external_id")
                        .HasFilter("external_id IS NOT NULL");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_asp_net_users_tenant_id");

                    b.HasIndex("Email", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_asp_net_users_email_tenant_id");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.ApplicationRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text")
                        .HasColumnName("id");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text")
                        .HasColumnName("concurrency_stamp");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("name");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("normalized_name");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_roles");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.Distributor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("CantonRegion")
                        .HasColumnType("text")
                        .HasColumnName("canton_region");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DistributionNetwork")
                        .HasColumnType("text")
                        .HasColumnName("distribution_network");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_distributors");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_distributors_tenant_id");

                    b.ToTable("distributors", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.DistributorDelegation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("DelegatedToDistributorId")
                        .HasColumnType("uuid")
                        .HasColumnName("delegated_to_distributor_id");

                    b.Property<Guid>("DelegatingDistributorId")
                        .HasColumnType("uuid")
                        .HasColumnName("delegating_distributor_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_from");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("valid_to");

                    b.HasKey("Id")
                        .HasName("pk_distributor_delegations");

                    b.HasIndex("DelegatedToDistributorId")
                        .HasDatabaseName("ix_distributor_delegations_delegated_to_distributor_id");

                    b.HasIndex("DelegatingDistributorId", "DelegatedToDistributorId")
                        .IsUnique()
                        .HasDatabaseName("ix_distributor_delegations_delegating_distributor_id_delegated");

                    b.ToTable("distributor_delegations", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.Order", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_id");

                    b.Property<Guid>("DistributorId")
                        .HasColumnType("uuid")
                        .HasColumnName("distributor_id");

                    b.Property<bool>("IsDelegated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_delegated");

                    b.Property<bool>("IsUnplanned")
                        .HasColumnType("boolean")
                        .HasColumnName("is_unplanned");

                    b.Property<string>("LocationReplacementReason")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("location_replacement_reason");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("order_number");

                    b.Property<Guid?>("OriginalSamplingLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("original_sampling_location_id");

                    b.Property<DateTime?>("PlannedDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("planned_date");

                    b.Property<string>("PreleveurId")
                        .HasColumnType("text")
                        .HasColumnName("preleveur_id");

                    b.Property<string>("SamplerComment")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("sampler_comment");

                    b.Property<Guid?>("SamplingLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("sampling_location_id");

                    b.Property<Guid?>("SamplingRoundId")
                        .HasColumnType("uuid")
                        .HasColumnName("sampling_round_id");

                    b.Property<int>("SortOrder")
                        .HasColumnType("integer")
                        .HasColumnName("sort_order");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<string>("StatusChangedBy")
                        .HasColumnType("text")
                        .HasColumnName("status_changed_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<int?>("UnplannedReason")
                        .HasColumnType("integer")
                        .HasColumnName("unplanned_reason");

                    b.Property<string>("UnplannedReasonDetails")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("unplanned_reason_details");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_orders");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_orders_created_by_id");

                    b.HasIndex("DistributorId")
                        .HasDatabaseName("ix_orders_distributor_id");

                    b.HasIndex("OrderNumber")
                        .IsUnique()
                        .HasDatabaseName("ix_orders_order_number");

                    b.HasIndex("OriginalSamplingLocationId")
                        .HasDatabaseName("ix_orders_original_sampling_location_id");

                    b.HasIndex("PreleveurId")
                        .HasDatabaseName("ix_orders_preleveur_id");

                    b.HasIndex("SamplingLocationId")
                        .HasDatabaseName("ix_orders_sampling_location_id");

                    b.HasIndex("SamplingRoundId", "SortOrder")
                        .HasDatabaseName("ix_orders_sampling_round_id_sort_order");

                    b.ToTable("orders", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.OrderAnalysisProfile", b =>
                {
                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<Guid>("AnalysisProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_profile_id");

                    b.HasKey("OrderId", "AnalysisProfileId")
                        .HasName("pk_order_analysis_profiles");

                    b.HasIndex("AnalysisProfileId")
                        .HasDatabaseName("ix_order_analysis_profiles_analysis_profile_id");

                    b.ToTable("order_analysis_profiles", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.OrderAuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("action");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("details");

                    b.Property<string>("NewValue")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("new_value");

                    b.Property<string>("OldValue")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("old_value");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<DateTime>("PerformedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("performed_at");

                    b.Property<string>("PerformedById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("performed_by_id");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_order_audit_logs");

                    b.HasIndex("OrderId")
                        .HasDatabaseName("ix_order_audit_logs_order_id");

                    b.HasIndex("PerformedById")
                        .HasDatabaseName("ix_order_audit_logs_performed_by_id");

                    b.HasIndex("TenantId", "PerformedAt")
                        .HasDatabaseName("ix_order_audit_logs_tenant_id_performed_at");

                    b.ToTable("order_audit_logs", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_permissions");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("ix_permissions_name");

                    b.ToTable("permissions", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.RolePermission", b =>
                {
                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("permission_id");

                    b.HasKey("RoleId", "PermissionId")
                        .HasName("pk_role_permissions");

                    b.HasIndex("PermissionId")
                        .HasDatabaseName("ix_role_permissions_permission_id");

                    b.ToTable("role_permissions", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.Sampling", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("BarcodeScannedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("barcode_scanned_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsValidated")
                        .HasColumnType("boolean")
                        .HasColumnName("is_validated");

                    b.Property<double?>("LocationLat")
                        .HasColumnType("double precision")
                        .HasColumnName("location_lat");

                    b.Property<double?>("LocationLng")
                        .HasColumnType("double precision")
                        .HasColumnName("location_lng");

                    b.Property<string>("Notes")
                        .HasColumnType("text")
                        .HasColumnName("notes");

                    b.Property<Guid>("OrderId")
                        .HasColumnType("uuid")
                        .HasColumnName("order_id");

                    b.Property<string>("PreleveurId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preleveur_id");

                    b.Property<string>("SampleBarcode")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("sample_barcode");

                    b.Property<DateTime>("SamplingDateTime")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("sampling_date_time");

                    b.Property<double?>("Temperature")
                        .HasColumnType("double precision")
                        .HasColumnName("temperature");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<DateTime?>("ValidatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("validated_at");

                    b.Property<string>("Weather")
                        .HasColumnType("text")
                        .HasColumnName("weather");

                    b.HasKey("Id")
                        .HasName("pk_samplings");

                    b.HasIndex("OrderId")
                        .IsUnique()
                        .HasDatabaseName("ix_samplings_order_id");

                    b.HasIndex("PreleveurId")
                        .HasDatabaseName("ix_samplings_preleveur_id");

                    b.HasIndex("SampleBarcode")
                        .IsUnique()
                        .HasDatabaseName("ix_samplings_sample_barcode")
                        .HasFilter("sample_barcode IS NOT NULL");

                    b.ToTable("samplings", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.SamplingLocation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<Guid>("DistributorId")
                        .HasColumnType("uuid")
                        .HasColumnName("distributor_id");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<double?>("Latitude")
                        .HasColumnType("double precision")
                        .HasColumnName("latitude");

                    b.Property<string>("LocationCode")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("location_code");

                    b.Property<double?>("Longitude")
                        .HasColumnType("double precision")
                        .HasColumnName("longitude");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid?>("SectorId")
                        .HasColumnType("uuid")
                        .HasColumnName("sector_id");

                    b.HasKey("Id")
                        .HasName("pk_sampling_locations");

                    b.HasIndex("DistributorId")
                        .HasDatabaseName("ix_sampling_locations_distributor_id");

                    b.HasIndex("SectorId")
                        .HasDatabaseName("ix_sampling_locations_sector_id");

                    b.ToTable("sampling_locations", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.SamplingLocationChangeRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DistributorId")
                        .HasColumnType("uuid")
                        .HasColumnName("distributor_id");

                    b.Property<string>("ProposedDescription")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("proposed_description");

                    b.Property<double?>("ProposedLatitude")
                        .HasColumnType("double precision")
                        .HasColumnName("proposed_latitude");

                    b.Property<string>("ProposedLocationCode")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("proposed_location_code");

                    b.Property<double?>("ProposedLongitude")
                        .HasColumnType("double precision")
                        .HasColumnName("proposed_longitude");

                    b.Property<string>("ProposedName")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("proposed_name");

                    b.Property<int>("RequestType")
                        .HasColumnType("integer")
                        .HasColumnName("request_type");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("requested_at");

                    b.Property<string>("RequestedById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("requested_by_id");

                    b.Property<string>("ReviewComment")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)")
                        .HasColumnName("review_comment");

                    b.Property<DateTime?>("ReviewedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("reviewed_at");

                    b.Property<string>("ReviewedById")
                        .HasColumnType("text")
                        .HasColumnName("reviewed_by_id");

                    b.Property<Guid?>("SamplingLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("sampling_location_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sampling_location_change_requests");

                    b.HasIndex("DistributorId")
                        .HasDatabaseName("ix_sampling_location_change_requests_distributor_id");

                    b.HasIndex("RequestedById")
                        .HasDatabaseName("ix_sampling_location_change_requests_requested_by_id");

                    b.HasIndex("ReviewedById")
                        .HasDatabaseName("ix_sampling_location_change_requests_reviewed_by_id");

                    b.HasIndex("SamplingLocationId")
                        .HasDatabaseName("ix_sampling_location_change_requests_sampling_location_id");

                    b.HasIndex("TenantId", "Status")
                        .HasDatabaseName("ix_sampling_location_change_requests_tenant_id_status");

                    b.ToTable("sampling_location_change_requests", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.SamplingPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_id");

                    b.Property<Guid>("DistributorId")
                        .HasColumnType("uuid")
                        .HasColumnName("distributor_id");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("RejectionReason")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("rejection_reason");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<DateTime?>("StatusChangedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("status_changed_at");

                    b.Property<string>("StatusChangedBy")
                        .HasColumnType("text")
                        .HasColumnName("status_changed_by");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.Property<int>("Year")
                        .HasColumnType("integer")
                        .HasColumnName("year");

                    b.HasKey("Id")
                        .HasName("pk_sampling_plans");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_sampling_plans_created_by_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sampling_plans_tenant_id");

                    b.HasIndex("DistributorId", "Year")
                        .IsUnique()
                        .HasDatabaseName("ix_sampling_plans_distributor_id_year");

                    b.ToTable("sampling_plans", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.SamplingPlanItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("AnalysisProfileId")
                        .HasColumnType("uuid")
                        .HasColumnName("analysis_profile_id");

                    b.Property<int>("FrequencyPerYear")
                        .HasColumnType("integer")
                        .HasColumnName("frequency_per_year");

                    b.PrimitiveCollection<List<int>>("PlannedMonths")
                        .IsRequired()
                        .HasColumnType("integer[]")
                        .HasColumnName("planned_months");

                    b.Property<Guid>("SamplingLocationId")
                        .HasColumnType("uuid")
                        .HasColumnName("sampling_location_id");

                    b.Property<Guid>("SamplingPlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("sampling_plan_id");

                    b.HasKey("Id")
                        .HasName("pk_sampling_plan_items");

                    b.HasIndex("AnalysisProfileId")
                        .HasDatabaseName("ix_sampling_plan_items_analysis_profile_id");

                    b.HasIndex("SamplingLocationId")
                        .HasDatabaseName("ix_sampling_plan_items_sampling_location_id");

                    b.HasIndex("SamplingPlanId")
                        .HasDatabaseName("ix_sampling_plan_items_sampling_plan_id");

                    b.ToTable("sampling_plan_items", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.SamplingRound", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("completed_at");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("CreatedById")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("created_by_id");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("deadline");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("description");

                    b.Property<Guid>("DistributorId")
                        .HasColumnType("uuid")
                        .HasColumnName("distributor_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Notes")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("notes");

                    b.Property<string>("PreleveurId")
                        .HasColumnType("text")
                        .HasColumnName("preleveur_id");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("text")
                        .HasColumnName("updated_by");

                    b.HasKey("Id")
                        .HasName("pk_sampling_rounds");

                    b.HasIndex("CreatedById")
                        .HasDatabaseName("ix_sampling_rounds_created_by_id");

                    b.HasIndex("PreleveurId")
                        .HasDatabaseName("ix_sampling_rounds_preleveur_id");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sampling_rounds_tenant_id");

                    b.HasIndex("DistributorId", "PreleveurId")
                        .HasDatabaseName("ix_sampling_rounds_distributor_id_preleveur_id");

                    b.HasIndex("TenantId", "Deadline")
                        .HasDatabaseName("ix_sampling_rounds_tenant_id_deadline");

                    b.ToTable("sampling_rounds", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.Sector", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uuid")
                        .HasColumnName("tenant_id");

                    b.HasKey("Id")
                        .HasName("pk_sectors");

                    b.HasIndex("TenantId")
                        .HasDatabaseName("ix_sectors_tenant_id");

                    b.HasIndex("Code", "TenantId")
                        .IsUnique()
                        .HasDatabaseName("ix_sectors_code_tenant_id");

                    b.ToTable("sectors", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.Tenant", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("Id")
                        .HasName("pk_tenants");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ix_tenants_code");

                    b.ToTable("tenants", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.UserDistributor", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<Guid>("DistributorId")
                        .HasColumnType("uuid")
                        .HasColumnName("distributor_id");

                    b.HasKey("UserId", "DistributorId")
                        .HasName("pk_user_distributors");

                    b.HasIndex("DistributorId")
                        .HasDatabaseName("ix_user_distributors_distributor_id");

                    b.ToTable("user_distributors", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_role_claims");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_role_claims_role_id");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text")
                        .HasColumnName("claim_type");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text")
                        .HasColumnName("claim_value");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("Id")
                        .HasName("pk_asp_net_user_claims");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_claims_user_id");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text")
                        .HasColumnName("provider_key");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text")
                        .HasColumnName("provider_display_name");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.HasKey("LoginProvider", "ProviderKey")
                        .HasName("pk_asp_net_user_logins");

                    b.HasIndex("UserId")
                        .HasDatabaseName("ix_asp_net_user_logins_user_id");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("RoleId")
                        .HasColumnType("text")
                        .HasColumnName("role_id");

                    b.HasKey("UserId", "RoleId")
                        .HasName("pk_asp_net_user_roles");

                    b.HasIndex("RoleId")
                        .HasDatabaseName("ix_asp_net_user_roles_role_id");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("text")
                        .HasColumnName("user_id");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text")
                        .HasColumnName("login_provider");

                    b.Property<string>("Name")
                        .HasColumnType("text")
                        .HasColumnName("name");

                    b.Property<string>("Value")
                        .HasColumnType("text")
                        .HasColumnName("value");

                    b.HasKey("UserId", "LoginProvider", "Name")
                        .HasName("pk_asp_net_user_tokens");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.AnalysisProfile", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_profiles_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.AnalysisProgram", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_programs_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.AnalysisProgramProfile", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.AnalysisProfile", "AnalysisProfile")
                        .WithMany("AnalysisProgramProfiles")
                        .HasForeignKey("AnalysisProfileId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_program_profiles_analysis_profiles_analysis_profil");

                    b.HasOne("AquaPlan.Domain.Entities.AnalysisProgram", "AnalysisProgram")
                        .WithMany("AnalysisProgramProfiles")
                        .HasForeignKey("AnalysisProgramId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_analysis_program_profiles_analysis_programs_analysis_progra");

                    b.Navigation("AnalysisProfile");

                    b.Navigation("AnalysisProgram");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.Tenant", "Tenant")
                        .WithMany("Users")
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_users_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.Distributor", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_distributors_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.DistributorDelegation", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.Distributor", "DelegatedToDistributor")
                        .WithMany()
                        .HasForeignKey("DelegatedToDistributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_distributor_delegations_distributors_delegated_to_distribut");

                    b.HasOne("AquaPlan.Domain.Entities.Distributor", "DelegatingDistributor")
                        .WithMany()
                        .HasForeignKey("DelegatingDistributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_distributor_delegations_distributors_delegating_distributor");

                    b.Navigation("DelegatedToDistributor");

                    b.Navigation("DelegatingDistributor");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.Order", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_users_created_by_id");

                    b.HasOne("AquaPlan.Domain.Entities.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_orders_distributors_distributor_id");

                    b.HasOne("AquaPlan.Domain.Entities.SamplingLocation", "OriginalSamplingLocation")
                        .WithMany()
                        .HasForeignKey("OriginalSamplingLocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_orders_sampling_locations_original_sampling_location_id");

                    b.HasOne("AquaPlan.Domain.Entities.AppUser", "Preleveur")
                        .WithMany()
                        .HasForeignKey("PreleveurId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_orders_users_preleveur_id");

                    b.HasOne("AquaPlan.Domain.Entities.SamplingLocation", "SamplingLocation")
                        .WithMany()
                        .HasForeignKey("SamplingLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_sampling_locations_sampling_location_id");

                    b.HasOne("AquaPlan.Domain.Entities.SamplingRound", "SamplingRound")
                        .WithMany("Orders")
                        .HasForeignKey("SamplingRoundId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_orders_sampling_rounds_sampling_round_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Distributor");

                    b.Navigation("OriginalSamplingLocation");

                    b.Navigation("Preleveur");

                    b.Navigation("SamplingLocation");

                    b.Navigation("SamplingRound");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.OrderAnalysisProfile", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.AnalysisProfile", "AnalysisProfile")
                        .WithMany()
                        .HasForeignKey("AnalysisProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_analysis_profiles_analysis_profiles_analysis_profile_");

                    b.HasOne("AquaPlan.Domain.Entities.Order", "Order")
                        .WithMany("OrderAnalysisProfiles")
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_analysis_profiles_orders_order_id");

                    b.Navigation("AnalysisProfile");

                    b.Navigation("Order");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.OrderAuditLog", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.Order", "Order")
                        .WithMany()
                        .HasForeignKey("OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_order_audit_logs_orders_order_id");

                    b.HasOne("AquaPlan.Domain.Entities.AppUser", "PerformedBy")
                        .WithMany()
                        .HasForeignKey("PerformedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_order_audit_logs_users_performed_by_id");

                    b.Navigation("Order");

                    b.Navigation("PerformedBy");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.RolePermission", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_permissions_permission_id");

                    b.HasOne("AquaPlan.Domain.Entities.ApplicationRole", "Role")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_role_permissions_roles_role_id");

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.Sampling", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.Order", "Order")
                        .WithOne("Sampling")
                        .HasForeignKey("AquaPlan.Domain.Entities.Sampling", "OrderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_samplings_orders_order_id");

                    b.HasOne("AquaPlan.Domain.Entities.AppUser", "Preleveur")
                        .WithMany()
                        .HasForeignKey("PreleveurId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_samplings_users_preleveur_id");

                    b.Navigation("Order");

                    b.Navigation("Preleveur");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.SamplingLocation", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.Distributor", "Distributor")
                        .WithMany("SamplingLocations")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sampling_locations_distributors_distributor_id");

                    b.HasOne("AquaPlan.Domain.Entities.Sector", "Sector")
                        .WithMany("SamplingLocations")
                        .HasForeignKey("SectorId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sampling_locations_sectors_sector_id");

                    b.Navigation("Distributor");

                    b.Navigation("Sector");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.SamplingLocationChangeRequest", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sampling_location_change_requests_distributors_distributor_");

                    b.HasOne("AquaPlan.Domain.Entities.AppUser", "RequestedBy")
                        .WithMany()
                        .HasForeignKey("RequestedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sampling_location_change_requests_users_requested_by_id");

                    b.HasOne("AquaPlan.Domain.Entities.AppUser", "ReviewedBy")
                        .WithMany()
                        .HasForeignKey("ReviewedById")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sampling_location_change_requests_users_reviewed_by_id");

                    b.HasOne("AquaPlan.Domain.Entities.SamplingLocation", "SamplingLocation")
                        .WithMany()
                        .HasForeignKey("SamplingLocationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sampling_location_change_requests_sampling_locations_sampli");

                    b.HasOne("AquaPlan.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sampling_location_change_requests_tenants_tenant_id");

                    b.Navigation("Distributor");

                    b.Navigation("RequestedBy");

                    b.Navigation("ReviewedBy");

                    b.Navigation("SamplingLocation");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.SamplingPlan", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sampling_plans_users_created_by_id");

                    b.HasOne("AquaPlan.Domain.Entities.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sampling_plans_distributors_distributor_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Distributor");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.SamplingPlanItem", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.AnalysisProfile", "AnalysisProfile")
                        .WithMany()
                        .HasForeignKey("AnalysisProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sampling_plan_items_analysis_profiles_analysis_profile_id");

                    b.HasOne("AquaPlan.Domain.Entities.SamplingLocation", "SamplingLocation")
                        .WithMany()
                        .HasForeignKey("SamplingLocationId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sampling_plan_items_sampling_locations_sampling_location_id");

                    b.HasOne("AquaPlan.Domain.Entities.SamplingPlan", "SamplingPlan")
                        .WithMany("Items")
                        .HasForeignKey("SamplingPlanId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sampling_plan_items_sampling_plans_sampling_plan_id");

                    b.Navigation("AnalysisProfile");

                    b.Navigation("SamplingLocation");

                    b.Navigation("SamplingPlan");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.SamplingRound", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.AppUser", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedById")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sampling_rounds_users_created_by_id");

                    b.HasOne("AquaPlan.Domain.Entities.Distributor", "Distributor")
                        .WithMany()
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_sampling_rounds_distributors_distributor_id");

                    b.HasOne("AquaPlan.Domain.Entities.AppUser", "Preleveur")
                        .WithMany()
                        .HasForeignKey("PreleveurId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .HasConstraintName("fk_sampling_rounds_users_preleveur_id");

                    b.Navigation("CreatedBy");

                    b.Navigation("Distributor");

                    b.Navigation("Preleveur");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.Sector", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.Tenant", "Tenant")
                        .WithMany()
                        .HasForeignKey("TenantId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sectors_tenants_tenant_id");

                    b.Navigation("Tenant");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.UserDistributor", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.Distributor", "Distributor")
                        .WithMany("UserDistributors")
                        .HasForeignKey("DistributorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_distributors_distributors_distributor_id");

                    b.HasOne("AquaPlan.Domain.Entities.AppUser", "User")
                        .WithMany("UserDistributors")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_user_distributors_users_user_id");

                    b.Navigation("Distributor");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_role_claims_asp_net_roles_role_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_claims_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_logins_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.ApplicationRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_roles_role_id");

                    b.HasOne("AquaPlan.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_roles_asp_net_users_user_id");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("AquaPlan.Domain.Entities.AppUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_asp_net_user_tokens_asp_net_users_user_id");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.AnalysisProfile", b =>
                {
                    b.Navigation("AnalysisProgramProfiles");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.AnalysisProgram", b =>
                {
                    b.Navigation("AnalysisProgramProfiles");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.AppUser", b =>
                {
                    b.Navigation("UserDistributors");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.Distributor", b =>
                {
                    b.Navigation("SamplingLocations");

                    b.Navigation("UserDistributors");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.Order", b =>
                {
                    b.Navigation("OrderAnalysisProfiles");

                    b.Navigation("Sampling");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.SamplingPlan", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.SamplingRound", b =>
                {
                    b.Navigation("Orders");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.Sector", b =>
                {
                    b.Navigation("SamplingLocations");
                });

            modelBuilder.Entity("AquaPlan.Domain.Entities.Tenant", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
