#!/usr/bin/env node
/**
 * AQ-416 — Generate version.ts for the Angular app.
 *
 * Resolution order:
 *   1. Environment variable APP_VERSION (CI / Docker override)
 *   2. GitVersion.yml (if present at repo root)
 *   3. git describe --tags (fallback to `git rev-parse --short HEAD`)
 *   4. package.json version
 *   5. Hard-coded "dev"
 *
 * This script is intentionally tolerant: any failure falls through to the
 * next source, and a final fallback ensures a valid version.ts is always
 * written so the Angular build never fails due to version resolution.
 */
import { execSync } from 'node:child_process';
import { readFileSync, writeFileSync, existsSync, mkdirSync } from 'node:fs';
import { dirname, resolve, join } from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = dirname(__filename);
const repoRoot = resolve(__dirname, '..');
const outputPath = join(
  repoRoot,
  'src',
  'AquaPlan.Web',
  'ClientApp',
  'src',
  'environments',
  'version.ts',
);

function tryGitVersionYml() {
  const ymlPath = join(repoRoot, 'GitVersion.yml');
  if (!existsSync(ymlPath)) {
    return null;
  }
  try {
    const content = readFileSync(ymlPath, 'utf8');
    // naive extraction of next-version: X.Y.Z
    const match = content.match(/next-version:\s*([0-9]+\.[0-9]+\.[0-9]+)/);
    return match ? match[1] : null;
  } catch {
    return null;
  }
}

function tryGit() {
  try {
    const describe = execSync('git describe --tags --always --dirty 2>/dev/null', {
      cwd: repoRoot,
      encoding: 'utf8',
    }).trim();
    return describe || null;
  } catch {
    try {
      const sha = execSync('git rev-parse --short HEAD 2>/dev/null', {
        cwd: repoRoot,
        encoding: 'utf8',
      }).trim();
      return sha || null;
    } catch {
      return null;
    }
  }
}

function tryGitCommit() {
  try {
    return execSync('git rev-parse --short HEAD 2>/dev/null', {
      cwd: repoRoot,
      encoding: 'utf8',
    }).trim();
  } catch {
    return '';
  }
}

function tryPackageVersion() {
  try {
    const pkgPath = join(
      repoRoot,
      'src',
      'AquaPlan.Web',
      'ClientApp',
      'package.json',
    );
    const pkg = JSON.parse(readFileSync(pkgPath, 'utf8'));
    return typeof pkg.version === 'string' && pkg.version !== '0.0.0'
      ? pkg.version
      : null;
  } catch {
    return null;
  }
}

function resolveVersion() {
  if (process.env.APP_VERSION && process.env.APP_VERSION.trim() !== '') {
    return process.env.APP_VERSION.trim();
  }
  const fromYml = tryGitVersionYml();
  const commit = tryGitCommit();
  if (fromYml) {
    return commit ? `${fromYml}-${commit}` : fromYml;
  }
  const fromGit = tryGit();
  if (fromGit) {
    return fromGit;
  }
  const fromPkg = tryPackageVersion();
  if (fromPkg) {
    return commit ? `${fromPkg}-${commit}` : fromPkg;
  }
  return 'dev';
}

function main() {
  let version = 'dev';
  let commit = '';
  try {
    version = resolveVersion();
    commit = tryGitCommit();
  } catch (err) {
    // tolerate any unexpected error
    console.warn('[generate-version] resolution failed, falling back to dev:', err?.message ?? err);
  }

  const outDir = dirname(outputPath);
  if (!existsSync(outDir)) {
    mkdirSync(outDir, { recursive: true });
  }

  const content = `// AUTO-GENERATED by scripts/generate-version.mjs — DO NOT EDIT. AQ-416.
export const VERSION = {
  version: ${JSON.stringify(version)},
  commit: ${JSON.stringify(commit)},
};
`;
  writeFileSync(outputPath, content, 'utf8');
  console.log(`[generate-version] wrote ${outputPath} → ${version}${commit ? ' (' + commit + ')' : ''}`);
}

main();
